### ISSUE TITLE
Fight the battle of converting everything to null safety

### ISSUE THREAD

**Issue by MrCsabaToth** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#118]
There was a 5+ hour battle where I tried to enhance and run ahead to get full null safety, but I got defeated, had to retreat and even the supposedly original starting point presented me with a sea of transitive dependency collision problems. Insane!
There'll be a few plugins which are quasi abandoned and have to find a replacement. Some plugins are already dead by not moving fast enough like `uni_links` -> `uni_links2` or `data_connection_checker` -> `internet_connection_checker`. Carnage is going on with `flutter_blue` (which is the most important plugin of all), `floor` and a few more.

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^4.0.1
  charts_flutter: ^0.10.0
  convert: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  device_info: ^2.0.0
  expandable: ^5.0.1
  fab_circular_menu: ^1.0.2
  file_picker: ^3.0.0
  floor:
    git:
      url: https://github.com/MrCsabaToth/floor.git
      path: floor
  flutter_blue:
    git:
      url: https://github.com/MrCsabaToth/flutter_blue.git
      ref: patch-1
  flutter_brand_icons: ^1.1.0
  get: ^4.0.0-nullsafety.2
  http: ^0.13.1
  http_parser: ^4.0.0
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  listview_utils:
    git:
      url: https://github.com/WaleedAlrashed/flutter-listutils.git
  loading_overlay: ^0.3.0
  meta: ^1.2.4
  preferences: any
  progress_indicators: ^0.1.5
  rxdart: ^0.26.0
  share_files_and_screenshot_widgets: ^1.0.3
  shared_preferences: ^2.0.5
  spinner_input: ^0.1.2
  sqflite: ^2.0.0+3
  tuple: ^2.0.0
  uni_links2: ^0.6.0+2
  url_launcher: ^6.0.3
  wakelock: ^0.5.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.12.2
  floor_generator:
    git:
      url: https://github.com/MrCsabaToth/floor.git
      path: floor_generator
  integration_test: ^1.0.2+2
  mockito: ^5.0.3
  mock_data: ^1.2.8
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```

possible problematic plugins will be `preferences`, I'll need to migrate to `pref` (see #107), `file_picker`, `share_files_and_screenshot_widgets` to name a few.
